backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - name: 'blog'
    label: 'Посты'
    folder: 'content/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Название', name: 'title', widget: 'string' }
      - { label: 'Дата', name: 'date', widget: 'datetime' }
      - { label: 'Теги', name: 'tags', widget: 'list' }
      - label: 'Категория'
        name: 'categories'
        widget: 'select'
        options: ['новости', 'статьи', 'работы']
        multiple: true
        min: 1
        max: 3
        default: ['новости']
      - { label: 'Обложка', name: 'banner', widget: 'image' }
      - { label: 'Текст', name: 'body', widget: 'markdown' }